enum ERoute {
  welcome,
  introduction,
  login,
  signUp,
  authGoogle,
  forgotPassword,
  pin,
  introductionSetupAccount,
  setDefault,
  main,
  notification,
  overviewReport,
  detailReport,
  addEditBudget,
  setting,
  overviewAccount,
  detailAccount,
  export,
  addEditAccount,
  addEditTransaction,
  detailTransaction,
  termOfCondition,

  addEditAccountType,
  addEditCategoryType,
  editTransactionType
}
